spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: ${GITHUB_CLIENT_ID:secretsecret}
                        client-secret: ${GITHUB_CLIENT_SECRET:secretsecret}
                        client-name: Github
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                        authorization-grant-type: authorization_code