spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: ${GITHUB_CLIENT_ID:clientid}
                        client-secret: ${GITHUB_CLIENT_SECRET:clientsecret}
                        redirect-uri: https://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}
                        scope: email, profile