spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID:secretsecret}
                        client-secret: ${GOOGLE_CLIENT_SECRET:secretsecret}
                        scope:
                            - openid
                            - profile
                        redirect-uri: https://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}