spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID:clientid}
                        client-secret: ${GOOGLE_CLIENT_SECRET:clientsecret}
                        redirect-uri: https://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}
                        scope: email, profile