spring:
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: ${KAKAO_CLIENT_ID:secretsecret}
                        client-secret: ${KAKAO_CLIENT_SECRET:secretsecret}
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
                            - profile_nickname
                            - profile_image
                        redirect-uri: https://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}
                        client-name: Kakao
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-info-authentication-method: header
                        user-name-attribute: id