spring:
    security:
        oauth2:
            client:
                registration:
                    naver:
                        client-id: ${NAVER_CLIENT_ID:secretsecret}
                        client-secret: ${NAVER_CLIENT_SECRET:secretsecret}
                        client-name: Naver
                        redirect-uri: https://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}
                        authorization-grant-type: authorization_code
                        scope:
                            - name
                            - email
                            - nickname
                            - profile_image
                provider:
                    naver:
                        authorization_uri: https://nid.naver.com/oauth2.0/authorize
                        token_uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user_name_attribute: response