server:
    servlet:
        context-path: /api
spring:
    application:
        name: server
    docker:
        compose:
            enabled: true
    flyway:
        enabled: true
        baseline-on-migrate: true
        baseline-version: 1
        fail-on-missing-locations: true

    security:
        allow-origins: "http://localhost:5173"
        oauth2:
            client:
                registration:
                    google:
                        client-id: "secretsecret"
                        client-secret: "secretsecret"
                        scope:
                            - openid
                            - profile

                    kakao:
                        client-id: "secretsecret"
                        client-secret: "secretsecret"
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
                            - profile_nickname
                            - profile_image
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                        client-name: Kakao

                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-info-authentication-method: header
                        user-name-attribute: id

jwt:
    key: asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf
login:
    success:
        redirect-url: http://localhost:5173/login-success
    cookie:
        access-token-key: Authorization
        refresh-token-key: Refresh