server:
    servlet:
        context-path: /api
        session:
            tracking-modes: cookie
spring:
    application:
        name: server
    docker:
        compose:
            enabled: false
    config:
        import:
            - classpath:/configuration/datasource.yml
            - classpath:/configuration/flyway.yml
            - classpath:/configuration/jwt.yml
            - classpath:/configuration/security.yml
            - classpath:/configuration/oauth2/kakao.yml
            - classpath:/configuration/oauth2/naver.yml
            - classpath:/configuration/oauth2/google.yml
            - classpath:/configuration/oauth2/github.yml
            - classpath:/configuration/smtp.yml
            - classpath:/configuration/local-storage.yml
            - classpath:/configuration/discord-logging.yml