server:
    servlet:
        context-path: /api
spring:
    application:
        name: server
    docker:
        compose:
            enabled: true
    config:
        import:
            - classpath:/configuration/datasource.yml
            - classpath:/configuration/flyway.yml
            - classpath:/configuration/jwt.yml
            - classpath:/configuration/security.yml
            - classpath:/configuration/oauth2/kakao.yml